---
services:
  art:
    build:
      context: ./dockerart
      dockerfile: Dockerfile
    #container_name: art
    volumes:
      - mydata:/boxfuse-sample-java-war-hello/target
  war:
    build:
      context: ./dockerwar
      dockerfile: Dockerfile
    volumes:
      - mydata:/usr/local/tomcat/webapps
    depends_on:
      - art
    ports:
      - "8080:8080"
volumes:
    mydata: