---
services:
  box:
    build:
      context: ./dockerart
      dockerfile: Dockerfile
    #container_name: art
    volumes:
      - ./vol:/boxfuse-sample-java-war-hello/target
  war:
    build:
      context: ./dockerwar
      dockerfile: Dockerfile
    volumes:
      - ./vol:/usr/local/tomcat/webapps
    depends_on:
      - box
    ports:
      - "8080:8080"